name: Quality Gate

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:

  quality:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read

    steps:

      - uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4

      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: table
          exit-code: '1'
          severity: CRITICAL,HIGH